// Generated by hand from supabase/migrations/20260522000000_initial_schema.sql
// Once a Supabase project is linked, replace with:
//   npx supabase gen types typescript --project-id <id> > src/types/database.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      managers: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string           // must match auth.users.id
          email: string
          full_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'managers_id_fkey'
            columns: ['id']
            isOneToOne: true
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
        ]
      }
      leagues: {
        Row: {
          id: string
          manager_id: string
          name: string
          description: string | null
          match_length_minutes: number
          overtime_enabled: boolean
          overtime_length_minutes: number
          penalties_enabled: boolean
          win_score: number | null
          points_regular_win: number
          points_ot_win: number
          points_penalties_win: number
          points_draw: number
          points_loss: number
          is_public: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          manager_id: string
          name: string
          description?: string | null
          match_length_minutes?: number
          overtime_enabled?: boolean
          overtime_length_minutes?: number
          penalties_enabled?: boolean
          win_score?: number | null
          points_regular_win?: number
          points_ot_win?: number
          points_penalties_win?: number
          points_draw?: number
          points_loss?: number
          is_public?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          manager_id?: string
          name?: string
          description?: string | null
          match_length_minutes?: number
          overtime_enabled?: boolean
          overtime_length_minutes?: number
          penalties_enabled?: boolean
          win_score?: number | null
          points_regular_win?: number
          points_ot_win?: number
          points_penalties_win?: number
          points_draw?: number
          points_loss?: number
          is_public?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'leagues_manager_id_fkey'
            columns: ['manager_id']
            isOneToOne: false
            referencedRelation: 'managers'
            referencedColumns: ['id']
          },
        ]
      }
      players: {
        Row: {
          id: string
          league_id: string
          manager_id: string | null
          full_name: string
          rating: number
          position: Database['public']['Enums']['position_type']
          stamina: Database['public']['Enums']['stamina_level']
          is_ghost: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          league_id: string
          manager_id?: string | null
          full_name: string
          rating: number
          position: Database['public']['Enums']['position_type']
          stamina: Database['public']['Enums']['stamina_level']
          is_ghost?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          league_id?: string
          manager_id?: string | null
          full_name?: string
          rating?: number
          position?: Database['public']['Enums']['position_type']
          stamina?: Database['public']['Enums']['stamina_level']
          is_ghost?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'players_league_id_fkey'
            columns: ['league_id']
            isOneToOne: false
            referencedRelation: 'leagues'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'players_manager_id_fkey'
            columns: ['manager_id']
            isOneToOne: false
            referencedRelation: 'managers'
            referencedColumns: ['id']
          },
        ]
      }
      tournaments: {
        Row: {
          id: string
          league_id: string
          name: string
          season: string
          status: Database['public']['Enums']['tournament_status']
          draft_status: Database['public']['Enums']['draft_status']
          start_date: string | null
          end_date: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          league_id: string
          name: string
          season: string
          status?: Database['public']['Enums']['tournament_status']
          draft_status?: Database['public']['Enums']['draft_status']
          start_date?: string | null
          end_date?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          league_id?: string
          name?: string
          season?: string
          status?: Database['public']['Enums']['tournament_status']
          draft_status?: Database['public']['Enums']['draft_status']
          start_date?: string | null
          end_date?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'tournaments_league_id_fkey'
            columns: ['league_id']
            isOneToOne: false
            referencedRelation: 'leagues'
            referencedColumns: ['id']
          },
        ]
      }
      teams: {
        Row: {
          id: string
          tournament_id: string
          league_id: string
          name: string
          color: string | null
          created_at: string
        }
        Insert: {
          id?: string
          tournament_id: string
          league_id: string
          name: string
          color?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          tournament_id?: string
          league_id?: string
          name?: string
          color?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'teams_tournament_id_fkey'
            columns: ['tournament_id']
            isOneToOne: false
            referencedRelation: 'tournaments'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'teams_league_id_fkey'
            columns: ['league_id']
            isOneToOne: false
            referencedRelation: 'leagues'
            referencedColumns: ['id']
          },
        ]
      }
      team_players: {
        Row: {
          id: string
          team_id: string
          player_id: string
          tournament_id: string
          drafted_at: string
        }
        Insert: {
          id?: string
          team_id: string
          player_id: string
          tournament_id: string
          drafted_at?: string
        }
        Update: {
          id?: string
          team_id?: string
          player_id?: string
          tournament_id?: string
          drafted_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'team_players_team_id_fkey'
            columns: ['team_id']
            isOneToOne: false
            referencedRelation: 'teams'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'team_players_player_id_fkey'
            columns: ['player_id']
            isOneToOne: false
            referencedRelation: 'players'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'team_players_tournament_id_fkey'
            columns: ['tournament_id']
            isOneToOne: false
            referencedRelation: 'tournaments'
            referencedColumns: ['id']
          },
        ]
      }
      matches: {
        Row: {
          id: string
          tournament_id: string
          league_id: string
          home_team_id: string
          away_team_id: string
          home_score: number | null
          away_score: number | null
          status: Database['public']['Enums']['match_status']
          victory_condition: Database['public']['Enums']['victory_condition'] | null
          match_date: string
          played_at: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tournament_id: string
          league_id: string
          home_team_id: string
          away_team_id: string
          home_score?: number | null
          away_score?: number | null
          status?: Database['public']['Enums']['match_status']
          victory_condition?: Database['public']['Enums']['victory_condition'] | null
          match_date: string
          played_at?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tournament_id?: string
          league_id?: string
          home_team_id?: string
          away_team_id?: string
          home_score?: number | null
          away_score?: number | null
          status?: Database['public']['Enums']['match_status']
          victory_condition?: Database['public']['Enums']['victory_condition'] | null
          match_date?: string
          played_at?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'matches_tournament_id_fkey'
            columns: ['tournament_id']
            isOneToOne: false
            referencedRelation: 'tournaments'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'matches_league_id_fkey'
            columns: ['league_id']
            isOneToOne: false
            referencedRelation: 'leagues'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'matches_home_team_id_fkey'
            columns: ['home_team_id']
            isOneToOne: false
            referencedRelation: 'teams'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'matches_away_team_id_fkey'
            columns: ['away_team_id']
            isOneToOne: false
            referencedRelation: 'teams'
            referencedColumns: ['id']
          },
        ]
      }
      match_events: {
        Row: {
          id: string
          match_id: string
          team_id: string
          player_id: string | null
          event_type: Database['public']['Enums']['event_type']
          minute: number
          description: string | null
          created_at: string
        }
        Insert: {
          id?: string
          match_id: string
          team_id: string
          player_id?: string | null
          event_type: Database['public']['Enums']['event_type']
          minute: number
          description?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          match_id?: string
          team_id?: string
          player_id?: string | null
          event_type?: Database['public']['Enums']['event_type']
          minute?: number
          description?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'match_events_match_id_fkey'
            columns: ['match_id']
            isOneToOne: false
            referencedRelation: 'matches'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'match_events_team_id_fkey'
            columns: ['team_id']
            isOneToOne: false
            referencedRelation: 'teams'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'match_events_player_id_fkey'
            columns: ['player_id']
            isOneToOne: false
            referencedRelation: 'players'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Views: Record<string, never>
    Functions: {
      is_league_manager: {
        Args: { p_league_id: string }
        Returns: boolean
      }
      league_is_public: {
        Args: { p_league_id: string }
        Returns: boolean
      }
    }
    Enums: {
      user_role:          'manager' | 'player'
      position_type:      'GK' | 'DEF' | 'MID' | 'FWD'
      stamina_level:      'Low' | 'Med' | 'High'
      victory_condition:  'REGULAR' | 'OVERTIME' | 'PENALTIES'
      match_status:       'scheduled' | 'live' | 'completed' | 'cancelled'
      event_type:         'goal' | 'assist' | 'yellow_card' | 'red_card' | 'substitution'
      tournament_status:  'draft' | 'active' | 'completed'
      draft_status:       'pending' | 'active' | 'completed'
    }
    CompositeTypes: Record<string, never>
  }
}

// ─── Convenience row-type aliases ─────────────────────────────────────────────
type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

type Enums<T extends keyof Database['public']['Enums']> =
  Database['public']['Enums'][T]

export type Manager          = Tables<'managers'>
export type League           = Tables<'leagues'>
export type Player           = Tables<'players'>
export type Tournament       = Tables<'tournaments'>
export type Team             = Tables<'teams'>
export type TeamPlayer       = Tables<'team_players'>
export type Match            = Tables<'matches'>
export type MatchEvent       = Tables<'match_events'>

export type UserRole         = Enums<'user_role'>
export type PositionType     = Enums<'position_type'>
export type StaminaLevel     = Enums<'stamina_level'>
export type VictoryCondition = Enums<'victory_condition'>
export type MatchStatus      = Enums<'match_status'>
export type EventType        = Enums<'event_type'>
export type TournamentStatus = Enums<'tournament_status'>
export type DraftStatus      = Enums<'draft_status'>
