// Auto-generated by: npx supabase gen types typescript --project-id <id> > src/types/database.ts
// Re-run this after every schema migration.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Tables will be generated here after migrations are applied
      [key: string]: {
        Row: Record<string, unknown>
        Insert: Record<string, unknown>
        Update: Record<string, unknown>
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      user_role: 'manager' | 'player'
      draft_status: 'pending' | 'active' | 'completed'
    }
  }
}
